version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/android"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    reviewers:
      - "AidanPark"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "ci"
    reviewers:
      - "AidanPark"

  - package-ecosystem: "npm"
    directory: "/android/www"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    reviewers:
      - "AidanPark"
